In [1]:
#import depedencies
import pandas as pd
import fiona
import folium
from folium import Choropleth, Circle, Marker
from folium.plugins import HeatMap, MarkerCluster
import math

In [3]:
#importing the dataFrames in Pandas
df_Pop = pd.read_csv("../data/Merged_data/Pop_dataUS.csv")
states_df = pd.read_csv("../data/statelatlong.csv")
#Rename state names column for simplicity
states_df.rename(columns = {'City':'State'}, inplace = True)
dibeties_df = pd.read_csv("../data/Merged_data/US-CDI_diabetes_prevalence.csv")

In [4]:
dibeties_df.head()

,Unnamed: 0,yearstart,locationabbr,locationdesc,question,datavalueunit,datavaluetype,datavalue
0,5841,2014,AK,Alaska,Prevalence of diagnosed diabetes among adults ...,%,Age-adjusted Prevalence,7.7
1,5927,2015,AK,Alaska,Prevalence of diagnosed diabetes among adults ...,%,Age-adjusted Prevalence,7.8
2,5869,2016,AK,Alaska,Prevalence of diagnosed diabetes among adults ...,%,Age-adjusted Prevalence,7.8
3,5926,2017,AK,Alaska,Prevalence of diagnosed diabetes among adults ...,%,Age-adjusted Prevalence,7.6
4,5856,2018,AK,Alaska,Prevalence of diagnosed diabetes among adults ...,%,Age-adjusted Prevalence,8.7