In [1]:
# !pip install sodapy

In [2]:
#!/usr/bin/env python

# make sure to install these packages before running:
# pip install pandas


import pandas as pd
from sodapy import Socrata

In [3]:
from config import App_token

In [4]:
# Unauthenticated client only works with public data sets. Note 'None'
# in place of application token, and no username or password:
client = Socrata("chronicdata.cdc.gov", App_token)

# results filtered by state: Texas and topic: Diabetes
results = client.get("g4ie-h725",locationabbr="TX",topic="Diabetes")

# Convert to pandas DataFrame
results_df = pd.DataFrame.from_records(results)

In [5]:
results_df.head()

,yearstart,yearend,locationabbr,locationdesc,datasource,topic,question,datavaluetype,datavaluefootnotesymbol,datavaluefootnote,...,topicid,questionid,datavaluetypeid,stratificationcategoryid1,stratificationid1,datavalue,datavaluealt,datavalueunit,lowconfidencelimit,highconfidencelimit
0,2015,2015,TX,Texas,SEDD; SID,Diabetes,Amputation of a lower extremity attributable t...,Number,-,No data available,...,DIA,DIA4_0,NMBR,GENDER,GENF,NaN,NaN,NaN,NaN,NaN
1,2017,2017,TX,Texas,SEDD; SID,Diabetes,Hospitalization with diabetes as a listed diag...,Number,-,No data available,...,DIA,DIA9_0,NMBR,RACE,BLK,NaN,NaN,NaN,NaN,NaN
2,2014,2014,TX,Texas,NVSS,Diabetes,Mortality with diabetic ketoacidosis reported ...,Number,NaN,NaN,...,DIA,DIA1_2,NMBR,GENDER,GENF,176,176,NaN,NaN,NaN
3,2015,2015,TX,Texas,SEDD; SID,Diabetes,Hospitalization with diabetes as a listed diag...,Crude Rate,-,No data available,...,DIA,DIA9_0,CRDRATE,GENDER,GENM,NaN,NaN,"cases per 10,000",NaN,NaN
4,2013,2013,TX,Texas,NVSS,Diabetes,Mortality due to diabetes reported as any list...,Number,NaN,NaN,...,DIA,DIA1_1,NMBR,GENDER,GENF,6476,6476,NaN,NaN,NaN

In [6]:
results_df["datavaluetype"].value_counts()

Age-adjusted Rate          244
Crude Rate                 244
Number                     244
Age-adjusted Prevalence    135
Crude Prevalence           132
Prevalence                   1
Name: datavaluetype, dtype: int64

In [7]:
results_df["yearstart"].value_counts()

2015    129
2016    128
2018    124
2014    123
2017    122
2013     87
2011     79
2019     78
2012     74
2010     55
2009      1
Name: yearstart, dtype: int64

In [9]:
results_df["question"].value_counts()

Mortality due to diabetes reported as any listed cause of death                                        240
Mortality with diabetic ketoacidosis reported as any listed cause of death                             240
Hospitalization with diabetes as a listed diagnosis                                                    126
Amputation of a lower extremity attributable to diabetes                                               126
Pneumococcal vaccination among noninstitutionalized adults aged 18-64 years with diagnosed diabetes     25
Influenza vaccination among noninstitutionalized adults aged >= 65 years with diagnosed diabetes        24
Prevalence of diagnosed diabetes among adults aged >= 18 years                                          24
Pneumococcal vaccination among noninstitutionalized adults aged >= 65 years with diagnosed diabetes     24
Dilated eye examination among adults aged >= 18 years with diagnosed diabetes                           23
Glycosylated hemoglobin measurement among adults aged >= 18 years with diagnosed diabetes               23
Prevalence of depressive disorders among adults aged >= 18 years with diagnosed diabetes                22
Adults with diagnosed diabetes aged >= 18 years who have taken a diabetes self-management course        21
Foot examination among adults aged >= 18 years with diagnosed diabetes                                  21
Influenza vaccination among noninstitutionalized adults aged 18-64 years with diagnosed diabetes        18
Prevalence of high blood pressure among adults aged >= 18 years with diagnosed diabetes                 12
Prevalence of high cholesterol among adults aged >= 18 years with diagnosed diabetes                    11
Visits to dentist or dental clinic among adults aged >= 18 years with diagnosed diabetes                10
Diabetes prevalence among women aged 18-44 years                                                         8
Prevalence of gestational diabetes                                                                       1
Prevalence of pre-pregnancy diabetes                                                                     1
Name: question, dtype: int64

In [10]:
dia_df = results_df.loc[results_df["topic"]=="Diabetes",:]
dia_df["question"].value_counts()

Mortality due to diabetes reported as any listed cause of death                                        240
Mortality with diabetic ketoacidosis reported as any listed cause of death                             240
Hospitalization with diabetes as a listed diagnosis                                                    126
Amputation of a lower extremity attributable to diabetes                                               126
Pneumococcal vaccination among noninstitutionalized adults aged 18-64 years with diagnosed diabetes     25
Influenza vaccination among noninstitutionalized adults aged >= 65 years with diagnosed diabetes        24
Prevalence of diagnosed diabetes among adults aged >= 18 years                                          24
Pneumococcal vaccination among noninstitutionalized adults aged >= 65 years with diagnosed diabetes     24
Dilated eye examination among adults aged >= 18 years with diagnosed diabetes                           23
Glycosylated hemoglobin measurement among adults aged >= 18 years with diagnosed diabetes               23
Prevalence of depressive disorders among adults aged >= 18 years with diagnosed diabetes                22
Adults with diagnosed diabetes aged >= 18 years who have taken a diabetes self-management course        21
Foot examination among adults aged >= 18 years with diagnosed diabetes                                  21
Influenza vaccination among noninstitutionalized adults aged 18-64 years with diagnosed diabetes        18
Prevalence of high blood pressure among adults aged >= 18 years with diagnosed diabetes                 12
Prevalence of high cholesterol among adults aged >= 18 years with diagnosed diabetes                    11
Visits to dentist or dental clinic among adults aged >= 18 years with diagnosed diabetes                10
Diabetes prevalence among women aged 18-44 years                                                         8
Prevalence of gestational diabetes                                                                       1
Prevalence of pre-pregnancy diabetes                                                                     1
Name: question, dtype: int64

In [11]:
mortality_df = dia_df.loc[dia_df["question"]=="Mortality due to diabetes reported as any listed cause of death",:]
mortality_df

,yearstart,yearend,locationabbr,locationdesc,datasource,topic,question,datavaluetype,datavaluefootnotesymbol,datavaluefootnote,...,topicid,questionid,datavaluetypeid,stratificationcategoryid1,stratificationid1,datavalue,datavaluealt,datavalueunit,lowconfidencelimit,highconfidencelimit
4,2013,2013,TX,Texas,NVSS,Diabetes,Mortality due to diabetes reported as any list...,Number,NaN,NaN,...,DIA,DIA1_1,NMBR,GENDER,GENF,6476,6476,NaN,NaN,NaN
5,2012,2012,TX,Texas,NVSS,Diabetes,Mortality due to diabetes reported as any list...,Number,NaN,NaN,...,DIA,DIA1_1,NMBR,GENDER,GENM,7272,7272,NaN,NaN,NaN
6,2010,2010,TX,Texas,NVSS,Diabetes,Mortality due to diabetes reported as any list...,Number,NaN,NaN,...,DIA,DIA1_1,NMBR,OVERALL,OVR,12883,12883,NaN,NaN,NaN
8,2010,2010,TX,Texas,NVSS,Diabetes,Mortality due to diabetes reported as any list...,Age-adjusted Rate,NaN,NaN,...,DIA,DIA1_1,AGEADJRATE,RACE,BLK,128.0,128.0,"cases per 100,000",122.8,133.1
9,2010,2010,TX,Texas,NVSS,Diabetes,Mortality due to diabetes reported as any list...,Number,NaN,NaN,...,DIA,DIA1_1,NMBR,GENDER,GENM,6876,6876,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
718,2019,2019,TX,Texas,NVSS,Diabetes,Mortality due to diabetes reported as any list...,Age-adjusted Rate,NaN,NaN,...,DIA,DIA1_1,AGEADJRATE,GENDER,GENF,65.5,65.5,"cases per 100,000",64.2,66.7
719,2019,2019,TX,Texas,NVSS,Diabetes,Mortality due to diabetes reported as any list...,Number,NaN,NaN,...,DIA,DIA1_1,NMBR,GENDER,GENM,13158,13158,Number,NaN,NaN
727,2019,2019,TX,Texas,NVSS,Diabetes,Mortality due to diabetes reported as any list...,Number,NaN,NaN,...,DIA,DIA1_1,NMBR,RACE,HIS,7161,7161,Number,NaN,NaN
732,2019,2019,TX,Texas,NVSS,Diabetes,Mortality due to diabetes reported as any list...,Number,NaN,NaN,...,DIA,DIA1_1,NMBR,RACE,BLK,3441,3441,Number,NaN,NaN
734,2019,2019,TX,Texas,NVSS,Diabetes,Mortality due to diabetes reported as any list...,Crude Rate,NaN,NaN,...,DIA,DIA1_1,CRDRATE,GENDER,GENF,71.6,71.6,"cases per 100,000",70.3,73.0

In [12]:
# url = "https://chronicdata.cdc.gov/resource/g4ie-h725.json?topic=Diabetes"