In [1]:
!pip install sodapy

Collecting sodapy
  Downloading sodapy-2.2.0-py2.py3-none-any.whl (15 kB)
Requirement already satisfied: requests>=2.28.1 in c:\users\30798\anaconda3\envs\pythondata\lib\site-packages (from sodapy) (2.28.1)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\30798\anaconda3\envs\pythondata\lib\site-packages (from requests>=2.28.1->sodapy) (2022.6.15)
Requirement already satisfied: idna<4,>=2.5 in c:\users\30798\anaconda3\envs\pythondata\lib\site-packages (from requests>=2.28.1->sodapy) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\30798\anaconda3\envs\pythondata\lib\site-packages (from requests>=2.28.1->sodapy) (1.26.12)
Requirement already satisfied: charset-normalizer<3,>=2 in c:\users\30798\anaconda3\envs\pythondata\lib\site-packages (from requests>=2.28.1->sodapy) (2.0.12)
Installing collected packages: sodapy
Successfully installed sodapy-2.2.0

In [2]:
#!/usr/bin/env python

# make sure to install these packages before running:
# pip install pandas


import pandas as pd
from sodapy import Socrata

# Unauthenticated client only works with public data sets. Note 'None'
# in place of application token, and no username or password:
client = Socrata("chronicdata.cdc.gov", None)

# Example authenticated client (needed for non-public datasets):
# client = Socrata(chronicdata.cdc.gov,
#                  MyAppToken,
#                  username="user@example.com",
#                  password="AFakePassword")

# First 2000 results, returned as JSON from API / converted to Python list of
# dictionaries by sodapy.
results = client.get("g4ie-h725", limit=1000)

# Convert to pandas DataFrame
results_df = pd.DataFrame.from_records(results)

Requirement already satisfied: sodapy in c:\users\30798\anaconda3\envs\pythondata\lib\site-packages (2.2.0)
Requirement already satisfied: requests>=2.28.1 in c:\users\30798\anaconda3\envs\pythondata\lib\site-packages (from sodapy) (2.28.1)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\30798\anaconda3\envs\pythondata\lib\site-packages (from requests>=2.28.1->sodapy) (2022.6.15)
Requirement already satisfied: idna<4,>=2.5 in c:\users\30798\anaconda3\envs\pythondata\lib\site-packages (from requests>=2.28.1->sodapy) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\30798\anaconda3\envs\pythondata\lib\site-packages (from requests>=2.28.1->sodapy) (1.26.12)
Requirement already satisfied: charset-normalizer<3,>=2 in c:\users\30798\anaconda3\envs\pythondata\lib\site-packages (from requests>=2.28.1->sodapy) (2.0.12)

WARNING:root:Requests made without an app_token will be subject to strict throttling limits.

In [4]:
results_df.head(10)

,yearstart,yearend,locationabbr,locationdesc,datasource,topic,question,datavaluetype,datavalue,datavaluealt,...,datavaluetypeid,stratificationcategoryid1,stratificationid1,:@computed_region_bxsw_vy29,:@computed_region_he4y_prf8,datavalueunit,lowconfidencelimit,highconfidencelimit,datavaluefootnotesymbol,datavaluefootnote
0,2010,2010,AK,Alaska,NVSS,Alcohol,Chronic liver disease mortality,Number,70,70,...,NMBR,OVERALL,OVR,51,1673,NaN,NaN,NaN,NaN,NaN
1,2017,2017,AK,Alaska,NVSS,Alcohol,Chronic liver disease mortality,Number,121,121,...,NMBR,OVERALL,OVR,51,1673,NaN,NaN,NaN,NaN,NaN
2,2018,2018,AK,Alaska,NVSS,Alcohol,Chronic liver disease mortality,Number,121,121,...,NMBR,OVERALL,OVR,51,1673,NaN,NaN,NaN,NaN,NaN
3,2011,2011,AK,Alaska,NVSS,Chronic Kidney Disease,Mortality with end-stage renal disease,Number,221,221,...,NMBR,RACE,WHT,51,1673,NaN,NaN,NaN,NaN,NaN
4,2012,2012,AK,Alaska,NVSS,Chronic Kidney Disease,Mortality with end-stage renal disease,Number,234,234,...,NMBR,RACE,WHT,51,1673,NaN,NaN,NaN,NaN,NaN
5,2015,2015,AK,Alaska,NVSS,Chronic Kidney Disease,Mortality with end-stage renal disease,Number,153,153,...,NMBR,GENDER,GENF,51,1673,NaN,NaN,NaN,NaN,NaN
6,2018,2018,AK,Alaska,NVSS,Cardiovascular Disease,Mortality from total cardiovascular diseases,Crude Rate,153.2,153.2,...,CRDRATE,OVERALL,OVR,51,1673,"cases per 100,000",144.3,162.2,NaN,NaN
7,2010,2010,AK,Alaska,NVSS,Cardiovascular Disease,Mortality from diseases of the heart,Number,707,707,...,NMBR,OVERALL,OVR,51,1673,NaN,NaN,NaN,NaN,NaN
8,2014,2014,AK,Alaska,NVSS,Cardiovascular Disease,Mortality from diseases of the heart,Number,489,489,...,NMBR,GENDER,GENM,51,1673,NaN,NaN,NaN,NaN,NaN
9,2016,2016,AK,Alaska,NVSS,Cardiovascular Disease,Mortality from diseases of the heart,Number,300,300,...,NMBR,GENDER,GENF,51,1673,NaN,NaN,NaN,NaN,NaN

In [5]:
results_df["datavaluetype"].unique()

array(['Number', 'Crude Rate', 'Crude Prevalence', 'Age-adjusted Rate',
       'Prevalence', 'US Dollars', 'Yes/No', 'Average Annual Number',
       'Percent'], dtype=object)

In [11]:
percent_df = results_df.loc[results_df["datavaluetype"]=="Percent",:]
percent_df
prevalence_df = results_df.loc[results_df["datavaluetype"]=="Prevalence",:]
prevalence_df

,yearstart,yearend,locationabbr,locationdesc,datasource,topic,question,datavaluetype,datavalue,datavaluealt,...,datavaluetypeid,stratificationcategoryid1,stratificationid1,:@computed_region_bxsw_vy29,:@computed_region_he4y_prf8,datavalueunit,lowconfidencelimit,highconfidencelimit,datavaluefootnotesymbol,datavaluefootnote
18,2010,2010,AL,Alabama,"Birth Certificate, NVSS",Diabetes,Prevalence of gestational diabetes,Prevalence,4.5,4.5,...,PREV,OVERALL,OVR,29,94,%,4.5,4.5,NaN,NaN
382,2010,2010,MT,Montana,"Birth Certificate, NVSS",Diabetes,Prevalence of gestational diabetes,Prevalence,3.81,3.81,...,PREV,OVERALL,OVR,2,2283,%,3.8,3.81,NaN,NaN
475,2010,2010,NJ,New Jersey,"Birth Certificate, NVSS",Diabetes,Prevalence of gestational diabetes,Prevalence,5.78,5.78,...,PREV,OVERALL,OVR,46,489,%,5.78,5.78,NaN,NaN

In [13]:
results_df["topic"].value_counts()

Cardiovascular Disease                             379
Asthma                                             164
Alcohol                                            127
Diabetes                                           112
Overarching Conditions                              72
Chronic Kidney Disease                              52
Tobacco                                             37
Reproductive Health                                 22
Cancer                                              13
Older Adults                                         9
Oral Health                                          7
Disability                                           3
Nutrition, Physical Activity, and Weight Status      2
Mental Health                                        1
Name: topic, dtype: int64

In [15]:
dia_df = results_df.loc[results_df["topic"]=="Diabetes",:]
dia_df["question"].value_counts()

Mortality due to diabetes reported as any listed cause of death               53
Hospitalization with diabetes as a listed diagnosis                           24
Amputation of a lower extremity attributable to diabetes                      19
Mortality with diabetic ketoacidosis reported as any listed cause of death    12
Prevalence of gestational diabetes                                             3
Prevalence of pre-pregnancy diabetes                                           1
Name: question, dtype: int64

In [16]:
mortality_df = dia_df.loc[dia_df["question"]=="Mortality due to diabetes reported as any listed cause of death",:]
mortality_df

,yearstart,yearend,locationabbr,locationdesc,datasource,topic,question,datavaluetype,datavalue,datavaluealt,...,datavaluetypeid,stratificationcategoryid1,stratificationid1,:@computed_region_bxsw_vy29,:@computed_region_he4y_prf8,datavalueunit,lowconfidencelimit,highconfidencelimit,datavaluefootnotesymbol,datavaluefootnote
12,2014,2014,AK,Alaska,NVSS,Diabetes,Mortality due to diabetes reported as any list...,Number,185,185,...,NMBR,GENDER,GENM,51,1673,NaN,NaN,NaN,NaN,NaN
31,2012,2012,AL,Alabama,NVSS,Diabetes,Mortality due to diabetes reported as any list...,Number,23,23,...,NMBR,RACE,HIS,29,94,NaN,NaN,NaN,NaN,NaN
104,2015,2015,CT,Connecticut,NVSS,Diabetes,Mortality due to diabetes reported as any list...,Number,937,937,...,NMBR,GENDER,GENF,24,1043,NaN,NaN,NaN,NaN,NaN
105,2016,2016,CT,Connecticut,NVSS,Diabetes,Mortality due to diabetes reported as any list...,Number,2189,2189,...,NMBR,OVERALL,OVR,24,1043,NaN,NaN,NaN,NaN,NaN
118,2016,2016,DC,District of Columbia,NVSS,Diabetes,Mortality due to diabetes reported as any list...,Number,222,222,...,NMBR,GENDER,GENF,44,1049,NaN,NaN,NaN,NaN,NaN
181,2012,2012,HI,Hawaii,NVSS,Diabetes,Mortality due to diabetes reported as any list...,Number,374,374,...,NMBR,GENDER,GENF,4,1657,NaN,NaN,NaN,NaN,NaN
182,2016,2016,HI,Hawaii,NVSS,Diabetes,Mortality due to diabetes reported as any list...,Number,64,64,...,NMBR,RACE,HIS,4,1657,NaN,NaN,NaN,NaN,NaN
200,2011,2011,IA,Iowa,NVSS,Diabetes,Mortality due to diabetes reported as any list...,Number,31,31,...,NMBR,RACE,HIS,16,281,NaN,NaN,NaN,NaN,NaN
219,2012,2012,ID,Idaho,NVSS,Diabetes,Mortality due to diabetes reported as any list...,Number,1076,1076,...,NMBR,OVERALL,OVR,5,1687,NaN,NaN,NaN,NaN,NaN
220,2013,2013,ID,Idaho,NVSS,Diabetes,Mortality due to diabetes reported as any list...,Number,508,508,...,NMBR,GENDER,GENF,5,1687,NaN,NaN,NaN,NaN,NaN
221,2017,2017,ID,Idaho,NVSS,Diabetes,Mortality due to diabetes reported as any list...,Number,821,821,...,NMBR,GENDER,GENM,5,1687,NaN,NaN,NaN,NaN,NaN
236,2011,2011,IL,Illinois,NVSS,Diabetes,Mortality due to diabetes reported as any list...,Number,7872,7872,...,NMBR,OVERALL,OVR,34,1795,NaN,NaN,NaN,NaN,NaN
237,2013,2013,IL,Illinois,NVSS,Diabetes,Mortality due to diabetes reported as any list...,Number,4065,4065,...,NMBR,GENDER,GENM,34,1795,NaN,NaN,NaN,NaN,NaN
238,2014,2014,IL,Illinois,NVSS,Diabetes,Mortality due to diabetes reported as any list...,Number,472,472,...,NMBR,RACE,HIS,34,1795,NaN,NaN,NaN,NaN,NaN
239,2015,2015,IL,Illinois,NVSS,Diabetes,Mortality due to diabetes reported as any list...,Crude Rate,64.1,64.1,...,CRDRATE,OVERALL,OVR,34,1795,"cases per 100,000",62.7,65.4,NaN,NaN
240,2016,2016,IL,Illinois,NVSS,Diabetes,Mortality due to diabetes reported as any list...,Number,495,495,...,NMBR,RACE,HIS,34,1795,NaN,NaN,NaN,NaN,NaN
250,2013,2013,IN,Indiana,NVSS,Diabetes,Mortality due to diabetes reported as any list...,Number,103,103,...,NMBR,RACE,HIS,35,1904,NaN,NaN,NaN,NaN,NaN
279,2018,2018,KY,Kentucky,NVSS,Diabetes,Mortality due to diabetes reported as any list...,Number,5975,5975,...,NMBR,RACE,WHT,36,235,NaN,NaN,NaN,NaN,NaN
291,2010,2010,LA,Louisiana,NVSS,Diabetes,Mortality due to diabetes reported as any list...,Number,1402,1402,...,NMBR,GENDER,GENF,22,1697,NaN,NaN,NaN,NaN,NaN
317,2017,2017,MD,Maryland,NVSS,Diabetes,Mortality due to diabetes reported as any list...,Number,2200,2200,...,NMBR,GENDER,GENF,45,1857,NaN,NaN,NaN,NaN,NaN
318,2018,2018,MD,Maryland,NVSS,Diabetes,Mortality due to diabetes reported as any list...,Number,110,110,...,NMBR,RACE,HIS,45,1857,NaN,NaN,NaN,NaN,NaN
347,2018,2018,MN,Minnesota,NVSS,Diabetes,Mortality due to diabetes reported as any list...,Number,3240,3240,...,NMBR,GENDER,GENM,1,392,NaN,NaN,NaN,NaN,NaN
360,2018,2018,MO,Missouri,NVSS,Diabetes,Mortality due to diabetes reported as any list...,Number,2644,2644,...,NMBR,GENDER,GENM,18,532,NaN,NaN,NaN,NaN,NaN
390,2016,2016,MT,Montana,NVSS,Diabetes,Mortality due to diabetes reported as any list...,Number,787,787,...,NMBR,RACE,WHT,2,2283,NaN,NaN,NaN,NaN,NaN
405,2014,2014,NC,North Carolina,NVSS,Diabetes,Mortality due to diabetes reported as any list...,Number,4246,4246,...,NMBR,GENDER,GENM,37,2390,NaN,NaN,NaN,NaN,NaN
406,2015,2015,NC,North Carolina,NVSS,Diabetes,Mortality due to diabetes reported as any list...,Number,4452,4452,...,NMBR,GENDER,GENM,37,2390,NaN,NaN,NaN,NaN,NaN
452,2010,2010,NE,Nebraska,NVSS,Diabetes,Mortality due to diabetes reported as any list...,Number,1668,1668,...,NMBR,OVERALL,OVR,19,2243,NaN,NaN,NaN,NaN,NaN
490,2011,2011,NJ,New Jersey,NVSS,Diabetes,Mortality due to diabetes reported as any list...,Number,3062,3062,...,NMBR,GENDER,GENM,46,489,NaN,NaN,NaN,NaN,NaN
491,2012,2012,NJ,New Jersey,NVSS,Diabetes,Mortality due to diabetes reported as any list...,Number,543,543,...,NMBR,RACE,HIS,46,489,NaN,NaN,NaN,NaN,NaN
492,2013,2013,NJ,New Jersey,NVSS,Diabetes,Mortality due to diabetes reported as any list...,Crude Rate,84.9,84.9,...,CRDRATE,GENDER,GENM,46,489,"cases per 100,000",81.8,88.0,NaN,NaN
493,2017,2017,NJ,New Jersey,NVSS,Diabetes,Mortality due to diabetes reported as any list...,Number,285,285,...,NMBR,RACE,API,46,489,NaN,NaN,NaN,NaN,NaN
511,2013,2013,NM,New Mexico,NVSS,Diabetes,Mortality due to diabetes reported as any list...,Number,480,480,...,NMBR,GENDER,GENM,11,616,NaN,NaN,NaN,NaN,NaN
573,2013,2013,PA,Pennsylvania,NVSS,Diabetes,Mortality due to diabetes reported as any list...,Number,5619,5619,...,NMBR,GENDER,GENM,48,2495,NaN,NaN,NaN,NaN,NaN
696,2012,2012,WY,Wyoming,NVSS,Diabetes,Mortality due to diabetes reported as any list...,Number,191,191,...,NMBR,GENDER,GENM,14,3084,NaN,NaN,NaN,NaN,NaN
698,2015,2015,CA,California,NVSS,Diabetes,Mortality due to diabetes reported as any list...,Number,14005,14005,...,NMBR,GENDER,GENF,8,1340,NaN,NaN,NaN,NaN,NaN
708,2015,2015,AR,Arkansas,NVSS,Diabetes,Mortality due to diabetes reported as any list...,Number,2056,2056,...,NMBR,RACE,WHT,15,998,NaN,NaN,NaN,NaN,NaN
714,2010,2010,AR,Arkansas,NVSS,Diabetes,Mortality due to diabetes reported as any list...,Number,1091,1091,...,NMBR,GENDER,GENF,15,998,NaN,NaN,NaN,NaN,NaN
743,2011,2011,AR,Arkansas,NVSS,Diabetes,Mortality due to diabetes reported as any list...,Number,2410,2410,...,NMBR,OVERALL,OVR,15,998,NaN,NaN,NaN,NaN,NaN
751,2014,2014,CT,Connecticut,NVSS,Diabetes,Mortality due to diabetes reported as any list...,Number,128,128,...,NMBR,RACE,HIS,24,1043,NaN,NaN,NaN,NaN,NaN
764,2015,2015,CT,Connecticut,NVSS,Diabetes,Mortality due to diabetes reported as any list...,Number,236,236,...,NMBR,RACE,BLK,24,1043,NaN,NaN,NaN,NaN,NaN
774,2017,2017,CT,Connecticut,NVSS,Diabetes,Mortality due to diabetes reported as any list...,Number,1025,1025,...,NMBR,GENDER,GENF,24,1043,NaN,NaN,NaN,NaN,NaN
777,2014,2014,CO,Colorado,NVSS,Diabetes,Mortality due to diabetes reported as any list...,Number,169,169,...,NMBR,RACE,BLK,9,1398,NaN,NaN,NaN,NaN,NaN
823,2011,2011,FL,Florida,NVSS,Diabetes,Mortality due to diabetes reported as any list...,Number,1499,1499,...,NMBR,RACE,HIS,30,1112,NaN,NaN,NaN,NaN,NaN
843,2018,2018,FL,Florida,NVSS,Diabetes,Mortality due to diabetes reported as any list...,Number,6974,6974,...,NMBR,GENDER,GENF,30,1112,NaN,NaN,NaN,NaN,NaN
848,2012,2012,DE,Delaware,NVSS,Diabetes,Mortality due to diabetes reported as any list...,Number,171,171,...,NMBR,RACE,BLK,43,1046,NaN,NaN,NaN,NaN,NaN
875,2019,2019,IN,Indiana,NVSS,Diabetes,Mortality due to diabetes reported as any list...,Number,3626,3626,...,NMBR,GENDER,GENM,35,1904,Number,NaN,NaN,NaN,NaN
901,2015,2015,AK,Alaska,NVSS,Diabetes,Mortality due to diabetes reported as any list...,Number,24,24,...,NMBR,RACE,API,51,1673,NaN,NaN,NaN,NaN,NaN
936,2019,2019,MD,Maryland,NVSS,Diabetes,Mortality due to diabetes reported as any list...,Number,3044,3044,...,NMBR,GENDER,GENM,45,1857,Number,NaN,NaN,NaN,NaN
942,2014,2014,AL,Alabama,NVSS,Diabetes,Mortality due to diabetes reported as any list...,Number,3319,3319,...,NMBR,OVERALL,OVR,29,94,NaN,NaN,NaN,NaN,NaN
946,2015,2015,AK,Alaska,NVSS,Diabetes,Mortality due to diabetes reported as any list...,Number,306,306,...,NMBR,OVERALL,OVR,51,1673,NaN,NaN,NaN,NaN,NaN
957,2016,2016,CA,California,NVSS,Diabetes,Mortality due to diabetes reported as any list...,Number,17515,17515,...,NMBR,GENDER,GENM,8,1340,NaN,NaN,NaN,NaN,NaN
983,2016,2016,AR,Arkansas,NVSS,Diabetes,Mortality due to diabetes reported as any list...,Number,2766,2766,...,NMBR,OVERALL,OVR,15,998,NaN,NaN,NaN,NaN,NaN
985,2019,2019,MO,Missouri,NVSS,Diabetes,Mortality due to diabetes reported as any list...,Number,2693,2693,...,NMBR,GENDER,GENM,18,532,Number,NaN,NaN,NaN,NaN

In [ ]:
url = "https://chronicdata.cdc.gov/resource/g4ie-h725.json?topic=Diabetes"